#!/usr/bin/env ruby
# frozen_string_literal: true

require "dependabot/file_fetchers"
require "dependabot/file_parsers"
require "dependabot/update_checkers"
require "dependabot/file_updaters"
require "dependabot/pull_request_creator"
require "dependabot/devbox"

repo      = ENV.fetch("GITHUB_REPOSITORY")
token     = ENV["GITHUB_ACCESS_TOKEN"] || ENV.fetch("GITHUB_TOKEN")
directory = ENV.fetch("DIRECTORY_PATH", "/")
branch    = ENV.fetch("BASE_BRANCH", nil)

credentials = [
  {
    "type" => "git_source",
    "host" => "github.com",
    "username" => "x-access-token",
    "password" => token
  }
]

source = Dependabot::Source.new(
  provider: "github",
  repo: repo,
  directory: directory,
  branch: branch
)

location = directory == "/" ? repo : "#{repo} (#{directory})"
puts "Fetching devbox files from #{location}"

fetcher = Dependabot::FileFetchers.for_package_manager("devbox").new(
  source: source,
  credentials: credentials
)

files  = fetcher.files
commit = fetcher.commit

parser = Dependabot::FileParsers.for_package_manager("devbox").new(
  dependency_files: files,
  source: source,
  credentials: credentials
)

dependencies = parser.parse
puts "Found #{dependencies.length} devbox package(s)"

dependencies.each do |dep| # rubocop:disable Metrics/BlockLength
  puts "Checking #{dep.name} (#{dep.version})..."

  checker = Dependabot::UpdateCheckers.for_package_manager("devbox").new(
    dependency: dep,
    dependency_files: files,
    credentials: credentials
  )

  if checker.up_to_date?
    puts "  up to date"
    next
  end

  requirements_to_unlock = checker.requirements_unlocked_or_can_be? ? :own : :none

  updated_deps =
    begin
      checker.updated_dependencies(requirements_to_unlock: requirements_to_unlock)
    rescue Dependabot::AllVersionsIgnored
      puts "  all versions ignored"
      next
    end

  updater = Dependabot::FileUpdaters.for_package_manager("devbox").new(
    dependencies: updated_deps,
    dependency_files: files,
    credentials: credentials
  )

  updated_files = updater.updated_dependency_files

  pr_creator = Dependabot::PullRequestCreator.new(
    source: source,
    base_commit: commit,
    dependencies: updated_deps,
    files: updated_files,
    credentials: credentials,
    label_language: true
  )

  pr = pr_creator.create
  if pr
    puts "  PR created: #{pr.html_url}"
  else
    puts "  PR already exists or no changes needed"
  end
end

puts "Done."
